services:
  ml_optimiser:
    ram_gb: 8
    storage_gb: 100
    availability: 50.0
    cpu: 8
    bandwidth_in: 2500
    bandwidth_out: 2500
    gpu: true
    access_control: true
    anti_tampering: false
    encryption: true
    carbon_intensity: 0.9
    pue: 1.0
    cost: 15

  video_stream_processor:
    ram_gb: 16
    storage_gb: 500
    availability: 95.0
    cpu: 16
    bandwidth_in: 5000
    bandwidth_out: 5000
    gpu: true
    access_control: true
    anti_tampering: true
    encryption: true
    carbon_intensity: 1.2
    pue: 1.1
    cost: 20

  data_analytics:
    ram_gb: 32
    storage_gb: 1000
    availability: 99.0
    cpu: 32
    bandwidth_in: 3000
    bandwidth_out: 3000
    gpu: false
    access_control: true
    anti_tampering: true
    encryption: true
    carbon_intensity: 0.7
    pue: 1.2
    cost: 25

  iot_controller:
    ram_gb: 4
    storage_gb: 50
    availability: 90.0
    cpu: 2
    bandwidth_in: 500
    bandwidth_out: 500
    gpu: false
    access_control: true
    anti_tampering: true
    encryption: false
    carbon_intensity: 0.4
    pue: 1.0
    cost: 10

  web_server:
    ram_gb: 8
    storage_gb: 100
    availability: 99.9
    cpu: 8
    bandwidth_in: 2000
    bandwidth_out: 2000
    gpu: false
    access_control: true
    anti_tampering: true
    encryption: true
    carbon_intensity: 1
    pue: 1.0
    cost: 12

  database_service:
    ram_gb: 64
    storage_gb: 2000
    availability: 99.95
    cpu: 64
    bandwidth_in: 8000
    bandwidth_out: 8000
    gpu: false
    access_control: true
    anti_tampering: true
    encryption: true
    carbon_intensity: 0.5 
    pue: 1.3
    cost: 40

  cloud_storage_service:
    ram_gb: 16
    storage_gb: 5000
    availability: 99.9
    cpu: 8
    bandwidth_in: 8000
    bandwidth_out: 8000
    gpu: false
    access_control: true
    anti_tampering: true
    encryption: true
    carbon_intensity: 1.8
    pue: 1.2
    cost: 30
